---
install:
  - wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.58.2/hugo_0.58.2_Linux-64bit.deb
  - sudo dpkg -i /tmp/hugo.deb

script:
  - hugo

deploy:
  - provider: pages
    local_dir: public
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    fqdn: jensen-zhang.site
    target_branch: master
    on:
      branch: hugo